services:
  - type: web
    name: portfolio
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 19.1.0
